// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using VRT.Resume.Domain.Entities;

namespace VRT.Resume.Persistence.Data
{
    public partial class AppDbContext : DbContext
    {
        public AppDbContext()
        {
        }

        public AppDbContext(DbContextOptions<AppDbContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Degree> Degree { get; set; }
        public virtual DbSet<EducationField> EducationField { get; set; }
        public virtual DbSet<Person> Person { get; set; }
        public virtual DbSet<PersonContact> PersonContact { get; set; }
        public virtual DbSet<PersonEducation> PersonEducation { get; set; }
        public virtual DbSet<PersonExperience> PersonExperience { get; set; }
        public virtual DbSet<PersonExperienceDuty> PersonExperienceDuty { get; set; }
        public virtual DbSet<PersonExperienceDutySkill> PersonExperienceDutySkill { get; set; }
        public virtual DbSet<PersonImage> PersonImage { get; set; }
        public virtual DbSet<PersonResume> PersonResume { get; set; }
        public virtual DbSet<PersonSkill> PersonSkill { get; set; }
        public virtual DbSet<ResumePersonSkill> ResumePersonSkill { get; set; }
        public virtual DbSet<School> School { get; set; }
        public virtual DbSet<SkillType> SkillType { get; set; }
        public virtual DbSet<UserPerson> UserPerson { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.ApplyConfiguration(new DegreeConfiguration());
            modelBuilder.ApplyConfiguration(new EducationFieldConfiguration());
            modelBuilder.ApplyConfiguration(new PersonConfiguration());
            modelBuilder.ApplyConfiguration(new PersonContactConfiguration());
            modelBuilder.ApplyConfiguration(new PersonEducationConfiguration());
            modelBuilder.ApplyConfiguration(new PersonExperienceConfiguration());
            modelBuilder.ApplyConfiguration(new PersonExperienceDutyConfiguration());
            modelBuilder.ApplyConfiguration(new PersonExperienceDutySkillConfiguration());
            modelBuilder.ApplyConfiguration(new PersonImageConfiguration());
            modelBuilder.ApplyConfiguration(new PersonResumeConfiguration());
            modelBuilder.ApplyConfiguration(new PersonSkillConfiguration());
            modelBuilder.ApplyConfiguration(new ResumePersonSkillConfiguration());
            modelBuilder.ApplyConfiguration(new SchoolConfiguration());
            modelBuilder.ApplyConfiguration(new SkillTypeConfiguration());
            modelBuilder.ApplyConfiguration(new UserPersonConfiguration());

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}
