// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
using VRT.Resume.Domain.Entities;



namespace VRT.Resume.Persistence.Data
{
    public class PersonExperienceDutySkillConfiguration : IEntityTypeConfiguration<PersonExperienceDutySkill>
    {
        public void Configure(EntityTypeBuilder<PersonExperienceDutySkill> entity)
        {
            entity.ToTable("PersonExperienceDutySkill", "Persons");

            entity.HasComment("Association between person's duty and skills used while performing on duty");

            entity.HasIndex(e => new { e.DutyId, e.SkillId })
                .HasName("UX_PersonExperienceSkill_DutyId_SkillId")
                .IsUnique();

            entity.HasOne(d => d.Duty)
                .WithMany(p => p.PersonExperienceDutySkill)
                .HasForeignKey(d => d.DutyId)
                .HasConstraintName("FK_PersonExperienceSkill_PersonExperienceDuty");

            entity.HasOne(d => d.Skill)
                .WithMany(p => p.PersonExperienceDutySkill)
                .HasForeignKey(d => d.SkillId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PersonExperienceSkill_PersonSkill");
        }
    }
}
