// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
using VRT.Resume.Domain.Entities;



namespace VRT.Resume.Persistence.Data
{
    public class PersonImageConfiguration : IEntityTypeConfiguration<PersonImage>
    {
        public void Configure(EntityTypeBuilder<PersonImage> entity)
        {
            entity.HasKey(e => e.ImageId);

            entity.ToTable("PersonImage", "Persons");

            entity.HasComment("Person profile images");

            entity.HasIndex(e => e.PersonId);

            entity.Property(e => e.ImageData).IsRequired();

            entity.Property(e => e.ImageType).HasMaxLength(30);

            entity.HasOne(d => d.Person)
                .WithMany(p => p.PersonImage)
                .HasForeignKey(d => d.PersonId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PersonImage_Person");
        }
    }
}
