// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
using VRT.Resume.Domain.Entities;



namespace VRT.Resume.Persistence.Data
{
    public class PersonEmailConfiguration : IEntityTypeConfiguration<PersonEmail>
    {
        public void Configure(EntityTypeBuilder<PersonEmail> entity)
        {
            entity.HasKey(e => new { e.EmailId, e.PersonId });

            entity.ToTable("PersonEmail", "Persons");

            entity.HasComment("Table with person emails");

            entity.Property(e => e.EmailId).ValueGeneratedOnAdd();

            entity.Property(e => e.EmailAdress)
                .IsRequired()
                .HasMaxLength(100);

            entity.Property(e => e.ModifiedDate)
                .HasColumnType("datetime")
                .HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Person)
                .WithMany(p => p.PersonEmail)
                .HasForeignKey(d => d.PersonId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PersonEmail_Person");
        }
    }
}
