// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
using VRT.Resume.Domain.Entities;



namespace VRT.Resume.Persistence.Data
{
    public class ResumePersonSkillConfiguration : IEntityTypeConfiguration<ResumePersonSkill>
    {
        public void Configure(EntityTypeBuilder<ResumePersonSkill> entity)
        {
            entity.HasKey(e => new { e.SkillId, e.ResumeId });

            entity.ToTable("ResumePersonSkill", "Resumes");

            entity.HasComment("Person skill for resume");

            entity.Property(e => e.SkillId).HasComment("Skill id from Person Skills");

            entity.Property(e => e.ResumeId).HasComment("");

            entity.Property(e => e.IsHidden).HasComment("The flag indicates wheter the skill should be hidden in profile skills section (main)");

            entity.Property(e => e.IsRelevent).HasComment("The flag indicates wheter the skill is significant for potencial employer");

            entity.HasOne(d => d.Resume)
                .WithMany(p => p.ResumePersonSkill)
                .HasForeignKey(d => d.ResumeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ResumePersonSkill_Resume");

            entity.HasOne(d => d.Skill)
                .WithMany(p => p.ResumePersonSkill)
                .HasForeignKey(d => d.SkillId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ResumePersonSkill_PersonSkill");
        }
    }
}
