// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
using VRT.Resume.Domain.Entities;



namespace VRT.Resume.Persistence.Data
{
    public class ResumeContactConfiguration : IEntityTypeConfiguration<ResumeContact>
    {
        public void Configure(EntityTypeBuilder<ResumeContact> entity)
        {
            entity.HasKey(e => new { e.ContactId, e.ResumeId });

            entity.ToTable("ResumeContact", "Resumes");

            entity.HasComment("Table of contacts connected with resume");

            entity.Property(e => e.ContactId).ValueGeneratedOnAdd();

            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");

            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50);

            entity.Property(e => e.Url).HasMaxLength(255);

            entity.Property(e => e.Value).IsRequired();

            entity.HasOne(d => d.Resume)
                .WithMany(p => p.ResumeContact)
                .HasForeignKey(d => d.ResumeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ResumeContact_Resume");
        }
    }
}
