// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VRT.Resume.Domain.Entities;

/// <summary>
/// Dictionary table with available degrees
/// </summary>
public partial class Degree
{
    public int DegreeId { get; set; }

    public string Name { get; set; }

    public string Abreviation { get; set; }

    public virtual ICollection<PersonEducation> PersonEducation { get; } = new List<PersonEducation>();
}