// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VRT.Resume.Domain.Entities;

/// <summary>
/// Education fields dictionary table
/// </summary>
public partial class EducationField
{
    public int EducationFieldId { get; set; }

    public string Name { get; set; }

    public virtual ICollection<PersonEducation> PersonEducation { get; } = new List<PersonEducation>();
}