// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace VRT.Resume.Domain.Entities
{
    /// <summary>
    /// Education fields dictionary table
    /// </summary>
    public partial class EducationField
    {
        public EducationField()
        {
            PersonEducation = new HashSet<PersonEducation>();
        }

        public int EducationFieldId { get; set; }
        public string Name { get; set; }

        public virtual ICollection<PersonEducation> PersonEducation { get; set; }
    }
}