// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VRT.Resume.Domain.Entities;

/// <summary>
/// Persons education entries
/// </summary>
public partial class PersonEducation
{
    public int EducationId { get; set; }

    public int PersonId { get; set; }

    public int SchoolId { get; set; }

    public DateTime FromDate { get; set; }

    public DateTime ToDate { get; set; }

    public int? DegreeId { get; set; }

    public int? EducationFieldId { get; set; }

    public string Specialization { get; set; }

    public string ThesisTitle { get; set; }

    public string Grade { get; set; }

    public DateTime ModifiedDate { get; set; }

    public virtual Degree Degree { get; set; }

    public virtual EducationField EducationField { get; set; }

    public virtual Person Person { get; set; }

    public virtual School School { get; set; }
}