// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace VRT.Resume.Domain.Entities
{
    /// <summary>
    /// Table of contacts connected with person
    /// </summary>
    partial class PersonContact: IPersonEntity
    {       
    }
}