// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace VRT.Resume.Domain.Entities
{
    /// <summary>
    /// Person profile images
    /// </summary>
    public partial class PersonImage
    {
        public int ImageId { get; set; }
        public int PersonId { get; set; }
        public byte[] ImageData { get; set; }
        public string ImageType { get; set; }

        public virtual Person Person { get; set; }
    }
}