// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VRT.Resume.Domain.Entities;

/// <summary>
/// Contains information about person duties for the experience entitty
/// </summary>
public partial class PersonExperienceDuty
{
    public int DutyId { get; set; }

    public int ExperienceId { get; set; }

    public string Name { get; set; }

    public virtual PersonExperience Experience { get; set; }

    public virtual ICollection<PersonExperienceDutySkill> PersonExperienceDutySkill { get; } = new List<PersonExperienceDutySkill>();
}