// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace VRT.Resume.Domain.Entities
{
    /// <summary>
    /// Contains information about person&apos;s work experience
    /// </summary>
    public partial class PersonExperience
    {
        public PersonExperience()
        {
            PersonExperienceDuty = new HashSet<PersonExperienceDuty>();
        }

        public int ExperienceId { get; set; }
        public int PersonId { get; set; }
        public string Position { get; set; }
        public string CompanyName { get; set; }
        public string Location { get; set; }
        public DateTime FromDate { get; set; }
        public DateTime? ToDate { get; set; }
        public DateTime ModifyDate { get; set; }

        public virtual Person Person { get; set; }
        public virtual ICollection<PersonExperienceDuty> PersonExperienceDuty { get; set; }
    }
}