// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace VRT.Resume.Domain.Entities
{
    /// <summary>
    /// Contains information about person&apos;s work experience
    /// </summary>
    public partial class PersonExperience : IPersonEntity
    {        
    }
}