// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace VRT.Resume.Domain.Entities
{
    /// <summary>
    /// Association between person&apos;s duty and skills used while performing on duty
    /// </summary>
    public partial class PersonExperienceDutySkill
    {
        public int Id { get; set; }
        public int DutyId { get; set; }
        public int SkillId { get; set; }

        public virtual PersonExperienceDuty Duty { get; set; }
        public virtual PersonSkill Skill { get; set; }
    }
}