// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace VRT.Resume.Domain.Entities
{
    /// <summary>
    /// Table contains full list of person skills
    /// </summary>
    public partial class PersonSkill
    {
        public PersonSkill()
        {
            PersonExperienceDutySkill = new HashSet<PersonExperienceDutySkill>();
            ResumePersonSkill = new HashSet<ResumePersonSkill>();
        }

        public int SkillId { get; set; }
        public int PersonId { get; set; }
        /// <summary>
        /// Skill type id
        /// </summary>
        public byte SkillTypeId { get; set; }
        /// <summary>
        /// Default name of the skill
        /// </summary>
        public string Name { get; set; }
        /// <summary>
        /// Knowledge level of the skill
        /// </summary>
        public string Level { get; set; }

        public virtual Person Person { get; set; }
        public virtual SkillType SkillType { get; set; }
        public virtual ICollection<PersonExperienceDutySkill> PersonExperienceDutySkill { get; set; }
        public virtual ICollection<ResumePersonSkill> ResumePersonSkill { get; set; }
    }
}