// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace VRT.Resume.Domain.Entities
{
    /// <summary>
    /// Table with person emails
    /// </summary>
    public partial class PersonEmail
    {
        public int EmailId { get; set; }
        public int PersonId { get; set; }
        public string EmailAdress { get; set; }
        public DateTime ModifiedDate { get; set; }

        public virtual Person Person { get; set; }
    }
}