// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VRT.Resume.Domain.Entities;

/// <summary>
/// Persons table
/// </summary>
public partial class Person
{
    public int PersonId { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public DateTime? DateOfBirth { get; set; }

    public DateTime ModifiedDate { get; set; }

    public virtual ICollection<PersonContact> PersonContact { get; set; } = new List<PersonContact>();

    public virtual ICollection<PersonEducation> PersonEducation { get; set; } = new List<PersonEducation>();

    public virtual ICollection<PersonExperience> PersonExperience { get; set; } = new List<PersonExperience>();

    public virtual ICollection<PersonImage> PersonImage { get; set; } = new List<PersonImage>();

    public virtual ICollection<PersonResume> PersonResume { get; set; } = new List<PersonResume>();

    public virtual ICollection<PersonSkill> PersonSkill { get; set; } = new List<PersonSkill>();

    public virtual ICollection<UserPerson> UserPerson { get; set; } = new List<UserPerson>();
}