// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VRT.Resume.Domain.Entities;

/// <summary>
/// Available schools
/// </summary>
public partial class School
{
    public int SchoolId { get; set; }

    public string Name { get; set; }

    public DateTime ModifiedDate { get; set; }

    public virtual ICollection<PersonEducation> PersonEducation { get; } = new List<PersonEducation>();
}