// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace VRT.Resume.Domain.Entities
{
    /// <summary>
    /// Skill types dictionary
    /// </summary>
    public partial class SkillType
    {
        public SkillType()
        {
            PersonSkill = new HashSet<PersonSkill>();
        }

        public byte SkillTypeId { get; set; }
        public string Name { get; set; }

        public virtual ICollection<PersonSkill> PersonSkill { get; set; }
    }
}