// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
using VRT.Resume.Domain.Entities;
using VRT.Resume.Persistence.Data;



namespace VRT.Resume.Persistence.Data.Configurations
{
    public class EducationFieldConfiguration : IEntityTypeConfiguration<EducationField>
    {
        public void Configure(EntityTypeBuilder<EducationField> entity)
        {
            entity.ToTable("EducationField", "Persons");

            entity.HasComment("Education fields dictionary table");

            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50);
        }
    }
}
