// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using VRT.Resume.Domain.Entities;
using VRT.Resume.Persistence.Data;

namespace VRT.Resume.Persistence.Data.Configurations
{
    public partial class PersonExperienceDutyConfiguration : IEntityTypeConfiguration<PersonExperienceDuty>
    {
        public void Configure(EntityTypeBuilder<PersonExperienceDuty> entity)
        {
            entity.HasKey(e => e.DutyId);

            entity.ToTable("PersonExperienceDuty", "Persons", tb => tb.HasComment("Contains information about person duties for the experience entitty"));

            entity.HasIndex(e => e.ExperienceId, "IX_PersonExperienceDuty_ExperienceId");

            entity.Property(e => e.Name)
            .IsRequired()
            .HasMaxLength(255);

            entity.HasOne(d => d.Experience).WithMany(p => p.PersonExperienceDuty)
            .HasForeignKey(d => d.ExperienceId)
            .HasConstraintName("FK_PersonExperienceDuty_PersonExperience");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<PersonExperienceDuty> entity);
    }
}
