// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using VRT.Resume.Domain.Entities;
using VRT.Resume.Persistence.Data;

namespace VRT.Resume.Persistence.Data.Configurations
{
    public partial class PersonExperienceDutySkillConfiguration : IEntityTypeConfiguration<PersonExperienceDutySkill>
    {
        public void Configure(EntityTypeBuilder<PersonExperienceDutySkill> entity)
        {
            entity.ToTable("PersonExperienceDutySkill", "Persons", tb => tb.HasComment("Association between person's duty and skills used while performing on duty"));

            entity.HasIndex(e => e.SkillId, "IX_PersonExperienceDutySkill_SkillId");

            entity.HasIndex(e => new { e.DutyId, e.SkillId }, "UX_PersonExperienceSkill_DutyId_SkillId").IsUnique();

            entity.HasOne(d => d.Duty).WithMany(p => p.PersonExperienceDutySkill)
            .HasForeignKey(d => d.DutyId)
            .HasConstraintName("FK_PersonExperienceSkill_PersonExperienceDuty");

            entity.HasOne(d => d.Skill).WithMany(p => p.PersonExperienceDutySkill)
            .HasForeignKey(d => d.SkillId)
            .HasConstraintName("FK_PersonExperienceSkill_PersonSkill");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<PersonExperienceDutySkill> entity);
    }
}
