// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
using VRT.Resume.Domain.Entities;
using VRT.Resume.Persistence.Data;



namespace VRT.Resume.Persistence.Data.Configurations
{
    public class PersonConfiguration : IEntityTypeConfiguration<Person>
    {
        public void Configure(EntityTypeBuilder<Person> entity)
        {
            entity.ToTable("Person", "Persons");

            entity.HasComment("Persons table");

            entity.Property(e => e.DateOfBirth).HasColumnType("date");

            entity.Property(e => e.FirstName)
                .IsRequired()
                .HasMaxLength(50);

            entity.Property(e => e.LastName).HasMaxLength(100);

            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");
        }
    }
}
